version: '3.3'
services:
  post_db:
    container_name: mongo-db
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    container_name:  frontend
    env_file: .env
    build: ./ui
    image: ${USERNAME}/ui:${VERS}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net
  post:
    container_name: frontent-post
    build: ./post-py
    image: ${USERNAME}/post:${VERS}
    networks:
      - front_net
      - back_net
  comment:
    container_name: frontend-comment
    build: ./comment
    image: ${USERNAME}/comment:${VERS}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:

